name: dart_to_js_script_rewriter
description: Replaces Dart script tags with JavaScript script tags,
             speeding up initial loads and reducing 404s. Use when
             ready to deploy.
author: Seth Ladd <sethladd@gmail.com>
version: 0.0.1
homepage: https://github.com/sethladd/dart_to_js_script_rewriter
dependencies:
  barback: ">=0.13.0 <0.14.0"
  html5lib: ">=0.10.0 <0.11.0"
dev_dependencies:
  browser: any
transformers:
- dart_to_js_script_rewriter
