name: dart_to_js_script_rewriter
description: Replaces Dart script tags with JavaScript script tags,
             speeding up initial loads and reducing 404s. Use when
             ready to deploy.
author: Seth Ladd <sethladd@gmail.com>
version: 0.1.0+4
homepage: https://github.com/Workiva/dart_to_js_script_rewriter
dependencies:
  barback: ">=0.15.0 <0.16.0"
  html: ">=0.12.0 <0.13.0"
dev_dependencies:
  browser: any
  test: any
transformers:
- dart_to_js_script_rewriter
